### ISSUE TITLE
realloc() error

### ISSUE THREAD

**Issue by biswajitSM** [PrincetonUniversity/ParallelChangePoint#1]
Hi @nsong06,
I compiled the changepoint code and ran the following command for processing:
    mpirun -np 2 Parallel-GM file.dat 0.05 0.95
But it showed error after checking for the nodes. Here is how the error looks like:
![screenshot from 2017-10-15 16-12-40](https://user-images.githubusercontent.com/12598051/31585636-869285c4-b1c5-11e7-9540-1eb0768266ee.png)

Have you faced this problem ever. Can you please suggest a solution for this.
System info:
Intel® Core™ i7-6500U CPU @ 2.50GHz × 4 , 64 bit
ubuntu 16.04 LTS
GNU C Library 2.23
OpenMPI 1.10.2

Thanks
Biswajit

**Comment by nsong06** [comment]
Hi Biswajit,

I have never seen the error before; however, after looking over the code, I believe I've found the error in main.c and fixed it on the master branch. Try running the new code and let me know if there are any more issues.

Thanks
Nancy

**Comment by biswajitSM** [comment]
Thanks a lot @nsong06 .
Now it works without error and quite fast. I compared with the results from changepoint-2005 program. And it gives way many changepoint with the same confidence interval. The Parallel-GM gives 10285 change points while the 2005-program gives 1385 points. The output from 2005-program fits well with the real binned trace (visually) while the output from parallel-GM doesn't.

Am I doing something wrong? Here is the the file with photon arrival time.
[Point_0.11uW_A5_0mV(66)_1.dat.tar.gz](https://github.com/PrincetonUniversity/ParallelChangePoint/files/1388802/Point_0.11uW_A5_0mV.66._1.dat.tar.gz)

the command was
    mpirun -np 2 Parallel-GM 'Point_0.11uW_A5_0mV(66)_1.dat' 0.1 0.9

And the last few lines of command out put was:
![screenshot from 2017-10-16 20-59-40](https://user-images.githubusercontent.com/12598051/31630927-6eec8d7c-b2b8-11e7-9073-fc4fa9fc2590.png)

I have forked the repository and will add more python-usage (analysis with examples) once it works properly.

Again thanks a lot for your time
Biswajit

**Comment by nsong06** [comment]
Hi Biswajit,
This program uses a different analysis and data than the 2005 program - the 2005 program takes photon arrival time as input, but this program requires the fluorescence intensity as input. You will note that the 2005 program uses a Poisson distribution to model photon count while this uses a Gaussian distribution.

Nancy

**Comment by biswajitSM** [comment]
Ah I see. stupid me. Anyway it's useful for many general purpose.
thanks a lot!
